### ISSUE TITLE
[Bug]: imagePullSecret not created correctly with disableLookups

### ISSUE THREAD

**Issue by grantat** [neo4j/helm-charts#190] opened 2023-07-11 14:46 UTC
### What happened?

Running `helm template` with an imagePullSecret (that already exists) set and `disableLookups` set to true generates a secret with no name.  To reproduce, use the following `values.yaml`:

```yaml
disableLookups: true
neo4j:
  name: "neo4j"
  passwordFromSecret: "auth-secret"
  edition: "community"
image:
  imagePullSecrets:
    - "pull-secret"
volumes:
  data:
    mode: "defaultStorageClass"
```

Use the following helm command to inspect the kubernetes manifests:

```bash
helm template neo4j/neo4j-standalone --version 4.4.18 --namespace test --values values.yaml --debug
```

Ideally, the new imagePullSecret would not be created and would instead use the existing imagePullSecret as defined by the `values.yaml`.

Related to #154 

### Chart Name

Standalone

### Chart Version

4.4.18

### Environment

Local Machine

### Relevant log output

```shell
---
# Source: neo4j-standalone/templates/neo4j-imagePullSecret.yaml
apiVersion: v1
kind: Secret
metadata:
   name: ""
   namespace: "test"
   labels:
     app: "neo4j"    
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment] 2023-07-12 09:42
thanks for reporting this @grantat ...Looking into this

**Comment by harshitsinghvi22** [comment] 2023-07-12 13:31
this is fix in the below PR and will be part of the next release

https://github.com/neo4j/helm-charts/pull/193

**Comment by harshitsinghvi22** [comment] 2023-07-12 13:33
fixed in 5.x too and will be part of the next release
https://github.com/neo4j/helm-charts/pull/194

**Comment by grantat** [comment] 2023-07-12 21:08
Hi @harshitsinghvi22, thanks for the quick response. However, if I'm understanding the proposed fix in #193 / #194, the Secret defined in https://github.com/neo4j/helm-charts/blob/fade332ca65677953ebf5382415419232980e5ce/neo4j/templates/neo4j-imagePullSecret.yaml would still be attempted to be created. I've already defined an imagePullSecret `pull-secret` and there is no need for the neo4j helm chart to create another resource of type `Secret` which would not be used by any of the remaining manifests. Maybe you can extend the `$.Values.disableLookups` conditional on https://github.com/neo4j/helm-charts/blob/fade332ca65677953ebf5382415419232980e5ce/neo4j/templates/neo4j-imagePullSecret.yaml#L15-L18 to be:

```yaml
      {{- if not $.Values.disableLookups -}}
        {{- $secret := (lookup "v1" "Secret" $.Release.Namespace $imagePullSecret) -}}
        {{- $secretExists = $secret | all -}}
      {{- else }}
         {{- $secretExists := true }} 
      {{- end -}}
```
as the neo4j chart does not have the ability to determine if the imagePullSecret already exists without lookups enabled.

**Comment by harshitsinghvi22** [comment] 2023-07-13 09:13
Hi @grantat since the disableLookups is set to true helm chart does not know if the secret exists hence the behaviour is correct where it assumes the secret is missing (incase of disableLookups set to true) and it will create the secret manifest

However , if you execute the same thing with helm install (setting disableLookups to false) it will not create secret since it will check for the secret existence and will find the same.

**Comment by hpdobrica** [comment] 2023-07-17 16:42
hello @harshitsinghvi22, i'm in a similar pickle as @grantat, and was wondering whether it'd make sense/be possible for us to rely on the lack of provided `values.image.imageCredentials` to know that the secret should not be created, even if the lookup is disabled?

I was under the impression that this is the intended behavior, since values comment on imageCredentials says "In case of a secret already pre-existing you don't need to mention the imageCredential , just add the pre-existing secretName to the imagePullSecret list and that will be used as an imagePullSecret"

I expected the value provided by `include "neo4j.imageCredentials.getImageCredential` to be empty as i haven't provided anything in imageCredentials values, but instead i got a secret with no name and docker config that looks like this:

`{"auths":{"%!s(<nil>)":{"username":"%!s(<nil>)","password":"%!s(<nil>)","email":"%!s(<nil>)","auth":"JSFzKDxuaWw+KTolIXMoPG5pbD4p"}}}`

my values look like this:
```yaml
  image:
    imagePullPolicy: IfNotPresent
    imagePullSecrets:
      - "sysdigcloud-pull-secret"
```

and rendered image looks like this:
```yaml
# Source: neo4j/charts/neo4j/templates/neo4j-imagePullSecret.yaml
apiVersion: v1
kind: Secret
metadata:
   name: ""
   namespace: "neo4j-helm-test"
   labels:
     app: "neo4j-cluster"    
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: eyJhdXRocyI6eyIlIXMoPG5pbD4pIjp7InVzZXJuYW1lIjoiJSFzKDxuaWw+KSIsInBhc3N3b3JkIjoiJSFzKDxuaWw+KSIsImVtYWlsIjoiJSFzKDxuaWw+KSIsImF1dGgiOiJKU0Z6S0R4dWFXdytLVG9sSVhNb1BHNXBiRDRwIn19fQ==

```

**Comment by harshitsinghvi22** [comment] 2023-07-18 09:24
@hpdobrica the statement "In case of a secret already pre-existing you don't need to mention the imageCredential , just add the pre-existing secretName to the imagePullSecret list and that will be used as an imagePullSecret" is made with the assumption that disableLookups is set to its default value "false"

If disableLookups is set to "true" helm charts will not assume that a secret already exists since it cannot verify its existence. Hence , the current behaviour is expected

Secret with no name issue is fixed and merged and will be part of the upcoming release

**Comment by hpdobrica** [comment] 2023-07-18 10:25
so if I'm understanding this well, if I have to disable lookups, there is no way for me to specify which existing secret to use without overriding it with fake secret containing `password":"%!s(<nil>)"`?

i guess ill have to find a workaround for this then 😬

**Comment by harshitsinghvi22** [comment] 2023-07-18 10:30
if you are disabling lookups then yes a secret will be created since it cannot know if a secret already exists. If you want to use an existing secret you will have to keep the default behaviour (lookups enabled)

**Comment by hpdobrica** [comment] 2023-07-18 10:45
wouldn't it be better if we just considered that no credentials are provided in values for a secret to be created (empty imageCredentials), and use that fact to just not create a secret? sorry that i'm going in circles with this, i don't see a downside to that approach (unless it's hard/impossible to implement), and there is definitely an upside as chart is more flexible?

Do you think it's worth it that I open another issue to pursue this, or am i missing something obvious making this sort of thing impossible to implement or in conflict with some other behavior?

**Comment by harshitsinghvi22** [comment] 2023-07-18 14:26
@hpdobrica thanks for your comments. I went back and discussed this with my team and we agreed to change the default behaviour of helm charts to assume the imagePullSecret exists when disableLookups is set to true. I will work on this and this feature should be available in the next release. I will reopen this issue to track this.

**Comment by harshitsinghvi22** [comment] 2023-07-27 21:17
This is implemented in the below PR's

https://github.com/neo4j/helm-charts/pull/206
https://github.com/neo4j/helm-charts/pull/205

Will be part of 5.10 release

**Closed as completed by harshitsinghvi22** 2023-07-27 21:17 UTC
Labels: bug
