### ISSUE TITLE
[Bug]: https://neo4j.github.io/helm-charts/index.yaml: 404 Not Found

### ISSUE THREAD

**Issue by haravich** [neo4j/helm-charts#347] opened 2024-08-28 06:39 UTC
### Contact Details

udthariprasath@gmail.com

### What happened?

We are seeing this below error when trying to fetch the helm chart
```
failed to fetch Helm repository index: failed to cache index to temporary file: failed to fetch
https://neo4j.github.io/helm-charts/index.yaml
: 404 Not Found
```
![image](https://github.com/user-attachments/assets/0cbb8b78-1299-43cc-bab9-7147fbdc3005)

### Chart Name

Neo4j

### Chart Version

5.12.0

### Environment

Microsoft Azure

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment] 2024-08-28 07:22
@haravich apologies for the inconvenience caused. The issue is fixed now

**Closed as completed by harshitsinghvi22** 2024-08-28 07:22 UTC
Labels: bug
